##################################################################################################
# City Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: city-srv
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "kube-training-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: city
    type: server
    chart: {{ include "kube-training-chart.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.country.items.service.type }}
  ports:
   - name: http
     port: {{ .Values.city.items.service.ports.httpPort }}
     targetPort: city-http-prt


##################################################################################################
# City Deployment
##################################################################################################
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: city-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.city.items.deployment.replicaCount }}

  #The Pods are labeled
  template:

    metadata:
      name: city-pod
      labels:
        app: city
        type: server
        chart: {{ include "kube-training-chart.name" . }}
        release: {{ .Release.Name }}

    spec:
      containers:
      - name: city-cntr
        ports:
          - name: city-http-prt
            containerPort: {{ .Values.city.items.deployment.containers.cityCntr.ports.http }}
        image: {{ .Values.city.items.deployment.containers.cityCntr.imageName }}
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 2
          httpGet:
            path: /actuator/health
            port: city-http-prt
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 20
          #Number of seconds after which the probe times out.
          #Defaults to 1 second. Minimum value is 1.
          timeoutSeconds: 2
          httpGet:
            path: /actuator/health
            port: city-http-prt
      restartPolicy: Always

  #defines how the Deployment finds which Pods to manage
  selector:
    matchLabels:
      app: city
      type: server
      chart: {{ include "kube-training-chart.name" . }}
      release: {{ .Release.Name }}