---
apiVersion: v1
kind: Pod
metadata:
 name: memory-leak-pod
 namespace: kube-training
spec:
 containers:
 - image: usikovich/memory-leak
   name: memory-leak-cntr
   resources:
    requests:
     cpu: 200m
     memory: 256Mi
    limits:
       cpu: 250m
       memory: 300Mi