---
apiVersion: v1
kind: LimitRange
metadata:
  name: example
spec:
  limits:


  #    Minimum/Maximum CPU and memory all the pod’s containers can request in total
  - type: Pod
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 1
      memory: 1Gi


  #       Default requests for resources that will be applied to containers
  #       if they don’t specify them explicitly
  - type: Container
    #    default request
    defaultRequest:
      cpu: 100m
      memory: 350Mi
    #    default limit
    default:
      cpu: 200m
      memory: 350Mi
   # Minimum/Maximum CPU and memory
    min:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 250m
      memory: 512Mi

  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 10Gi