---
apiVersion: v1
kind: ResourceQuota
metadata:
 namespace: kube-training
 name: kube-training-rq
spec:
 hard:
  #resource restriction
  requests.cpu: 400m
  requests.memory: 200Mi
  limits.cpu: 600m
  limits.memory: 500Mi

  #number restriction
  pods: 2
  replicationcontrollers: 5
  secrets: 10
  configmaps: 10
  persistentvolumeclaims: 4
  services: 5
  services.loadbalancers: 1
  services.nodeports: 2
  #Only two PerVolumClaims can claim storage with the ssd StorageClass
  ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2
