---
apiVersion: v1
kind: Pod
metadata:
  name: city-pod-with-requested-resources
  namespace: kube-training
spec:
  containers:
  - image: usikovich/cityservice
    name: citycntr
    resources:
      requests:
        cpu: 110m
        memory: 200Mi
      limits:
        cpu: 120m
        memory: 320Mi
